<a href="https://colab.research.google.com/github/dikshasinghhh/Deep-Learning/blob/main/ANN/Combined_Power_Plant_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.15.0'

# Data Preprocessing

In [ ]:
dataset= pd.read_excel('Folds5x2_pp.xlsx')
x= dataset.iloc[:, :-1].values
y= dataset.iloc[:,-1].values

In [ ]:
print(x)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [ ]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


splitting the dataset

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.2, random_state=0)

#Feature Scaling

# Initalizing the ANN

In [ ]:
ann=tf.keras.models.Sequential()

Adding the Input layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,))

#Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

#Training the ANN

In [ ]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 2s 3ms/step - loss: 6342.3145
Epoch 2/100
240/240 [==============================] - 1s 3ms/step - loss: 376.2050
Epoch 3/100
240/240 [==============================] - 1s 3ms/step - loss: 346.1978
Epoch 4/100
240/240 [==============================] - 1s 3ms/step - loss: 309.6611
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 270.5891
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 230.2254
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 190.6498
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 150.9754
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 116.3847
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 87.1503
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 64.5183
Epoch 12/100
240/240 [==============================] - 0s 2ms/step - loss:

predicting the test set results

In [ ]:
y_pred = ann.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 1ms/step
[[432.65 431.23]
 [463.87 460.01]
 [467.4  461.14]
 ...
 [474.63 473.26]
 [441.37 438.  ]
 [460.62 463.28]]
